name: Coin Alert Bot

on:
  schedule:
    - cron: '*/10 * * * *' # Her 10 dakikada bir çalıştır

  workflow_dispatch: # Manuel olarak da çalıştırabilme

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'

      - name: Gerekli Kütüphaneleri Yükle
        run: pip install requests python-telegram-bot

      - name: Python Betiğini Çalıştır
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python script.py
